language: node_js
node_js:
  - 12
cache: npm
script:
  - npm install
  - npm run build
after_success:
  - mkdir -p artifacts/
  - tar -zcvf artifacts/KoishiApp.tgz dist/
  - echo "[Latest Build](KoishiApp.tgz)" > artifacts/index.md
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_token
  local_dir: artifacts/
  on:
    branch: main
